# Generated by Django 5.2.4 on 2026-03-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
